name: Pinecone Query

on:
  schedule:
    - cron:  '0 6 * * *'
  workflow_dispatch:

jobs:
  query_pinecone:
    runs-on: ubuntu-latest
    env:
      PINECONE_KEY: ${{ secrets.PINECONE_KEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pinecone-client
      
    - name: Query Pinecone Database
      run: python .github/scripts/query_pinecone.py

